/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SplatRouteImport } from './routes/$'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as DasborRouteImport } from './routes/dasbor'
import { Route as FiturRouteImport } from './routes/fitur'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MasukRouteImport } from './routes/masuk'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminArsitekturRouteImport } from './routes/admin.arsitektur'
import { Route as AdminBeritaRouteImport } from './routes/admin.berita'
import { Route as AdminPaketRouteImport } from './routes/admin.paket'
import { Route as AdminPesanWaRouteImport } from './routes/admin.pesan-wa'
import { Route as AdminProfilRouteImport } from './routes/admin.profil'
import { Route as AdminPromosiGambarRouteImport } from './routes/admin.promosi-gambar'
import { Route as AdminPromosiPengaturanRouteImport } from './routes/admin.promosi-pengaturan'
import { Route as AdminPromosiVideoRouteImport } from './routes/admin.promosi-video'
import { Route as AdminRsvpRouteImport } from './routes/admin.rsvp'
import { Route as AdminSistemRouteImport } from './routes/admin.sistem'
import { Route as AdminTemplatesAiRouteImport } from './routes/admin.templates-ai'
import { Route as AdminTransaksiRouteImport } from './routes/admin.transaksi'
import { Route as BeritaIndexRouteImport } from './routes/berita.index'
import { Route as BeritaSlugRouteImport } from './routes/berita.$slug'
import { Route as DasborIndexRouteImport } from './routes/dasbor.index'
import { Route as DasborAcaraRouteImport } from './routes/dasbor.acara'
import { Route as DasborCeritaRouteImport } from './routes/dasbor.cerita'
import { Route as DasborGaleriRouteImport } from './routes/dasbor.galeri'
import { Route as DasborHadiahRouteImport } from './routes/dasbor.hadiah'
import { Route as DasborMempelaiRouteImport } from './routes/dasbor.mempelai'
import { Route as DasborPaketRouteImport } from './routes/dasbor.paket'
import { Route as DasborPembelianRouteImport } from './routes/dasbor.pembelian'
import { Route as DasborProfilRouteImport } from './routes/dasbor.profil'
import { Route as DasborSebarRouteImport } from './routes/dasbor.sebar'
import { Route as DasborTamuRouteImport } from './routes/dasbor.tamu'
import { Route as DasborTemplateRouteImport } from './routes/dasbor.template'
import { Route as DemoAiSlugRouteImport } from './routes/demo-ai.$slug'
import { Route as DemoIndexRouteImport } from './routes/demo.index'
import { Route as DemoSlugRouteImport } from './routes/demo.$slug'
import { Route as AdminAsetIndexRouteImport } from './routes/admin.aset.index'
import { Route as AdminDeteksiAsetIndexRouteImport } from './routes/admin.deteksi-aset.index'
import { Route as AdminDoaIndexRouteImport } from './routes/admin.doa.index'
import { Route as AdminDoaIdRouteImport } from './routes/admin.doa.$id'
import { Route as AdminDoaBaruRouteImport } from './routes/admin.doa.baru'
import { Route as AdminGaleriAsetIndexRouteImport } from './routes/admin.galeri-aset.index'
import { Route as AdminGaleriAsetUploadRouteImport } from './routes/admin.galeri-aset.upload'
import { Route as AdminMusikIndexRouteImport } from './routes/admin.musik.index'
import { Route as AdminMusikBaruRouteImport } from './routes/admin.musik.baru'
import { Route as AdminPenggunaIndexRouteImport } from './routes/admin.pengguna.index'
import { Route as AdminPenggunaIdRouteImport } from './routes/admin.pengguna.$id'
import { Route as AdminPenggunaBaruRouteImport } from './routes/admin.pengguna.baru'
import { Route as AdminPromosiTemplateIndexRouteImport } from './routes/admin.promosi-template.index'
import { Route as AdminQuotesIndexRouteImport } from './routes/admin.quotes.index'
import { Route as AdminQuotesBaruRouteImport } from './routes/admin.quotes.baru'
import { Route as AdminSuratIndexRouteImport } from './routes/admin.surat.index'
import { Route as AdminSuratBaruRouteImport } from './routes/admin.surat.baru'
import { Route as AdminTemplateIndexRouteImport } from './routes/admin.template.index'
import { Route as AdminTemplateIdRouteImport } from './routes/admin.template.$id'
import { Route as AdminTemplateUploadRouteImport } from './routes/admin.template.upload'
import { Route as AdminUndanganIndexRouteImport } from './routes/admin.undangan.index'
import { Route as AdminUndanganIdRouteImport } from './routes/admin.undangan.$id'
import { Route as AdminUndanganBaruRouteImport } from './routes/admin.undangan.baru'
import { Route as DasborBukuTamuIndexRouteImport } from './routes/dasbor.buku-tamu.index'
import { Route as DasborBukuTamuEventIdRouteImport } from './routes/dasbor.buku-tamu.$eventId'
import { Route as DasborUndanganIndexRouteImport } from './routes/dasbor.undangan.index'
import { Route as DasborUndanganIdRouteImport } from './routes/dasbor.undangan.$id'
import { Route as AdminPromosiTemplateIdAsetRouteImport } from './routes/admin.promosi-template.$id.aset'
import { Route as DasborBukuTamuEventIdIndexRouteImport } from './routes/dasbor.buku-tamu.$eventId.index'
import { Route as DasborBukuTamuEventIdAnalitikRouteImport } from './routes/dasbor.buku-tamu.$eventId.analitik'
import { Route as DasborBukuTamuEventIdKehadiranRouteImport } from './routes/dasbor.buku-tamu.$eventId.kehadiran'
import { Route as DasborBukuTamuEventIdLogRouteImport } from './routes/dasbor.buku-tamu.$eventId.log'
import { Route as DasborBukuTamuEventIdPengaturanRouteImport } from './routes/dasbor.buku-tamu.$eventId.pengaturan'
import { Route as DasborBukuTamuEventIdUcapanRouteImport } from './routes/dasbor.buku-tamu.$eventId.ucapan'
import { Route as DasborBukuTamuEventIdTamuIndexRouteImport } from './routes/dasbor.buku-tamu.$eventId.tamu.index'
import { Route as DasborBukuTamuEventIdTamuGuestIdRouteImport } from './routes/dasbor.buku-tamu.$eventId.tamu.$guestId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const DasborRoute = DasborRouteImport.update({
  id: '/dasbor',
  path: '/dasbor',
  getParentRoute: () => rootRouteImport,
} as any)
const FiturRoute = FiturRouteImport.update({
  id: '/fitur',
  path: '/fitur',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MasukRoute = MasukRouteImport.update({
  id: '/masuk',
  path: '/masuk',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminArsitekturRoute = AdminArsitekturRouteImport.update({
  id: '/arsitektur',
  path: '/arsitektur',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBeritaRoute = AdminBeritaRouteImport.update({
  id: '/berita',
  path: '/berita',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPaketRoute = AdminPaketRouteImport.update({
  id: '/paket',
  path: '/paket',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPesanWaRoute = AdminPesanWaRouteImport.update({
  id: '/pesan-wa',
  path: '/pesan-wa',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProfilRoute = AdminProfilRouteImport.update({
  id: '/profil',
  path: '/profil',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPromosiGambarRoute = AdminPromosiGambarRouteImport.update({
  id: '/promosi-gambar',
  path: '/promosi-gambar',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPromosiPengaturanRoute = AdminPromosiPengaturanRouteImport.update({
  id: '/promosi-pengaturan',
  path: '/promosi-pengaturan',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPromosiVideoRoute = AdminPromosiVideoRouteImport.update({
  id: '/promosi-video',
  path: '/promosi-video',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRsvpRoute = AdminRsvpRouteImport.update({
  id: '/rsvp',
  path: '/rsvp',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSistemRoute = AdminSistemRouteImport.update({
  id: '/sistem',
  path: '/sistem',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTemplatesAiRoute = AdminTemplatesAiRouteImport.update({
  id: '/templates-ai',
  path: '/templates-ai',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTransaksiRoute = AdminTransaksiRouteImport.update({
  id: '/transaksi',
  path: '/transaksi',
  getParentRoute: () => AdminRoute,
} as any)
const BeritaIndexRoute = BeritaIndexRouteImport.update({
  id: '/berita/',
  path: '/berita/',
  getParentRoute: () => rootRouteImport,
} as any)
const BeritaSlugRoute = BeritaSlugRouteImport.update({
  id: '/berita/$slug',
  path: '/berita/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const DasborIndexRoute = DasborIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DasborRoute,
} as any)
const DasborAcaraRoute = DasborAcaraRouteImport.update({
  id: '/acara',
  path: '/acara',
  getParentRoute: () => DasborRoute,
} as any)
const DasborCeritaRoute = DasborCeritaRouteImport.update({
  id: '/cerita',
  path: '/cerita',
  getParentRoute: () => DasborRoute,
} as any)
const DasborGaleriRoute = DasborGaleriRouteImport.update({
  id: '/galeri',
  path: '/galeri',
  getParentRoute: () => DasborRoute,
} as any)
const DasborHadiahRoute = DasborHadiahRouteImport.update({
  id: '/hadiah',
  path: '/hadiah',
  getParentRoute: () => DasborRoute,
} as any)
const DasborMempelaiRoute = DasborMempelaiRouteImport.update({
  id: '/mempelai',
  path: '/mempelai',
  getParentRoute: () => DasborRoute,
} as any)
const DasborPaketRoute = DasborPaketRouteImport.update({
  id: '/paket',
  path: '/paket',
  getParentRoute: () => DasborRoute,
} as any)
const DasborPembelianRoute = DasborPembelianRouteImport.update({
  id: '/pembelian',
  path: '/pembelian',
  getParentRoute: () => DasborRoute,
} as any)
const DasborProfilRoute = DasborProfilRouteImport.update({
  id: '/profil',
  path: '/profil',
  getParentRoute: () => DasborRoute,
} as any)
const DasborSebarRoute = DasborSebarRouteImport.update({
  id: '/sebar',
  path: '/sebar',
  getParentRoute: () => DasborRoute,
} as any)
const DasborTamuRoute = DasborTamuRouteImport.update({
  id: '/tamu',
  path: '/tamu',
  getParentRoute: () => DasborRoute,
} as any)
const DasborTemplateRoute = DasborTemplateRouteImport.update({
  id: '/template',
  path: '/template',
  getParentRoute: () => DasborRoute,
} as any)
const DemoAiSlugRoute = DemoAiSlugRouteImport.update({
  id: '/demo-ai/$slug',
  path: '/demo-ai/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoIndexRoute = DemoIndexRouteImport.update({
  id: '/demo/',
  path: '/demo/',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoSlugRoute = DemoSlugRouteImport.update({
  id: '/demo/$slug',
  path: '/demo/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAsetIndexRoute = AdminAsetIndexRouteImport.update({
  id: '/aset/',
  path: '/aset/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDeteksiAsetIndexRoute = AdminDeteksiAsetIndexRouteImport.update({
  id: '/deteksi-aset/',
  path: '/deteksi-aset/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDoaIndexRoute = AdminDoaIndexRouteImport.update({
  id: '/doa/',
  path: '/doa/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDoaIdRoute = AdminDoaIdRouteImport.update({
  id: '/doa/$id',
  path: '/doa/$id',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDoaBaruRoute = AdminDoaBaruRouteImport.update({
  id: '/doa/baru',
  path: '/doa/baru',
  getParentRoute: () => AdminRoute,
} as any)
const AdminGaleriAsetIndexRoute = AdminGaleriAsetIndexRouteImport.update({
  id: '/galeri-aset/',
  path: '/galeri-aset/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminGaleriAsetUploadRoute = AdminGaleriAsetUploadRouteImport.update({
  id: '/galeri-aset/upload',
  path: '/galeri-aset/upload',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMusikIndexRoute = AdminMusikIndexRouteImport.update({
  id: '/musik/',
  path: '/musik/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMusikBaruRoute = AdminMusikBaruRouteImport.update({
  id: '/musik/baru',
  path: '/musik/baru',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPenggunaIndexRoute = AdminPenggunaIndexRouteImport.update({
  id: '/pengguna/',
  path: '/pengguna/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPenggunaIdRoute = AdminPenggunaIdRouteImport.update({
  id: '/pengguna/$id',
  path: '/pengguna/$id',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPenggunaBaruRoute = AdminPenggunaBaruRouteImport.update({
  id: '/pengguna/baru',
  path: '/pengguna/baru',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPromosiTemplateIndexRoute =
  AdminPromosiTemplateIndexRouteImport.update({
    id: '/promosi-template/',
    path: '/promosi-template/',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminQuotesIndexRoute = AdminQuotesIndexRouteImport.update({
  id: '/quotes/',
  path: '/quotes/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminQuotesBaruRoute = AdminQuotesBaruRouteImport.update({
  id: '/quotes/baru',
  path: '/quotes/baru',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSuratIndexRoute = AdminSuratIndexRouteImport.update({
  id: '/surat/',
  path: '/surat/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSuratBaruRoute = AdminSuratBaruRouteImport.update({
  id: '/surat/baru',
  path: '/surat/baru',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTemplateIndexRoute = AdminTemplateIndexRouteImport.update({
  id: '/template/',
  path: '/template/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTemplateIdRoute = AdminTemplateIdRouteImport.update({
  id: '/template/$id',
  path: '/template/$id',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTemplateUploadRoute = AdminTemplateUploadRouteImport.update({
  id: '/template/upload',
  path: '/template/upload',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUndanganIndexRoute = AdminUndanganIndexRouteImport.update({
  id: '/undangan/',
  path: '/undangan/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUndanganIdRoute = AdminUndanganIdRouteImport.update({
  id: '/undangan/$id',
  path: '/undangan/$id',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUndanganBaruRoute = AdminUndanganBaruRouteImport.update({
  id: '/undangan/baru',
  path: '/undangan/baru',
  getParentRoute: () => AdminRoute,
} as any)
const DasborBukuTamuIndexRoute = DasborBukuTamuIndexRouteImport.update({
  id: '/buku-tamu/',
  path: '/buku-tamu/',
  getParentRoute: () => DasborRoute,
} as any)
const DasborBukuTamuEventIdRoute = DasborBukuTamuEventIdRouteImport.update({
  id: '/buku-tamu/$eventId',
  path: '/buku-tamu/$eventId',
  getParentRoute: () => DasborRoute,
} as any)
const DasborUndanganIndexRoute = DasborUndanganIndexRouteImport.update({
  id: '/undangan/',
  path: '/undangan/',
  getParentRoute: () => DasborRoute,
} as any)
const DasborUndanganIdRoute = DasborUndanganIdRouteImport.update({
  id: '/undangan/$id',
  path: '/undangan/$id',
  getParentRoute: () => DasborRoute,
} as any)
const AdminPromosiTemplateIdAsetRoute =
  AdminPromosiTemplateIdAsetRouteImport.update({
    id: '/promosi-template/$id/aset',
    path: '/promosi-template/$id/aset',
    getParentRoute: () => AdminRoute,
  } as any)
const DasborBukuTamuEventIdIndexRoute =
  DasborBukuTamuEventIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => DasborBukuTamuEventIdRoute,
  } as any)
const DasborBukuTamuEventIdAnalitikRoute =
  DasborBukuTamuEventIdAnalitikRouteImport.update({
    id: '/analitik',
    path: '/analitik',
    getParentRoute: () => DasborBukuTamuEventIdRoute,
  } as any)
const DasborBukuTamuEventIdKehadiranRoute =
  DasborBukuTamuEventIdKehadiranRouteImport.update({
    id: '/kehadiran',
    path: '/kehadiran',
    getParentRoute: () => DasborBukuTamuEventIdRoute,
  } as any)
const DasborBukuTamuEventIdLogRoute =
  DasborBukuTamuEventIdLogRouteImport.update({
    id: '/log',
    path: '/log',
    getParentRoute: () => DasborBukuTamuEventIdRoute,
  } as any)
const DasborBukuTamuEventIdPengaturanRoute =
  DasborBukuTamuEventIdPengaturanRouteImport.update({
    id: '/pengaturan',
    path: '/pengaturan',
    getParentRoute: () => DasborBukuTamuEventIdRoute,
  } as any)
const DasborBukuTamuEventIdUcapanRoute =
  DasborBukuTamuEventIdUcapanRouteImport.update({
    id: '/ucapan',
    path: '/ucapan',
    getParentRoute: () => DasborBukuTamuEventIdRoute,
  } as any)
const DasborBukuTamuEventIdTamuIndexRoute =
  DasborBukuTamuEventIdTamuIndexRouteImport.update({
    id: '/tamu/',
    path: '/tamu/',
    getParentRoute: () => DasborBukuTamuEventIdRoute,
  } as any)
const DasborBukuTamuEventIdTamuGuestIdRoute =
  DasborBukuTamuEventIdTamuGuestIdRouteImport.update({
    id: '/tamu/$guestId',
    path: '/tamu/$guestId',
    getParentRoute: () => DasborBukuTamuEventIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/admin': typeof AdminRouteWithChildren
  '/dasbor': typeof DasborRouteWithChildren
  '/fitur': typeof FiturRoute
  '/login': typeof LoginRoute
  '/masuk': typeof MasukRoute
  '/admin/arsitektur': typeof AdminArsitekturRoute
  '/admin/berita': typeof AdminBeritaRoute
  '/admin/paket': typeof AdminPaketRoute
  '/admin/pesan-wa': typeof AdminPesanWaRoute
  '/admin/profil': typeof AdminProfilRoute
  '/admin/promosi-gambar': typeof AdminPromosiGambarRoute
  '/admin/promosi-pengaturan': typeof AdminPromosiPengaturanRoute
  '/admin/promosi-video': typeof AdminPromosiVideoRoute
  '/admin/rsvp': typeof AdminRsvpRoute
  '/admin/sistem': typeof AdminSistemRoute
  '/admin/templates-ai': typeof AdminTemplatesAiRoute
  '/admin/transaksi': typeof AdminTransaksiRoute
  '/berita/$slug': typeof BeritaSlugRoute
  '/dasbor/acara': typeof DasborAcaraRoute
  '/dasbor/cerita': typeof DasborCeritaRoute
  '/dasbor/galeri': typeof DasborGaleriRoute
  '/dasbor/hadiah': typeof DasborHadiahRoute
  '/dasbor/mempelai': typeof DasborMempelaiRoute
  '/dasbor/paket': typeof DasborPaketRoute
  '/dasbor/pembelian': typeof DasborPembelianRoute
  '/dasbor/profil': typeof DasborProfilRoute
  '/dasbor/sebar': typeof DasborSebarRoute
  '/dasbor/tamu': typeof DasborTamuRoute
  '/dasbor/template': typeof DasborTemplateRoute
  '/demo-ai/$slug': typeof DemoAiSlugRoute
  '/demo/$slug': typeof DemoSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/berita/': typeof BeritaIndexRoute
  '/dasbor/': typeof DasborIndexRoute
  '/demo/': typeof DemoIndexRoute
  '/admin/doa/$id': typeof AdminDoaIdRoute
  '/admin/doa/baru': typeof AdminDoaBaruRoute
  '/admin/galeri-aset/upload': typeof AdminGaleriAsetUploadRoute
  '/admin/musik/baru': typeof AdminMusikBaruRoute
  '/admin/pengguna/$id': typeof AdminPenggunaIdRoute
  '/admin/pengguna/baru': typeof AdminPenggunaBaruRoute
  '/admin/quotes/baru': typeof AdminQuotesBaruRoute
  '/admin/surat/baru': typeof AdminSuratBaruRoute
  '/admin/template/$id': typeof AdminTemplateIdRoute
  '/admin/template/upload': typeof AdminTemplateUploadRoute
  '/admin/undangan/$id': typeof AdminUndanganIdRoute
  '/admin/undangan/baru': typeof AdminUndanganBaruRoute
  '/dasbor/buku-tamu/$eventId': typeof DasborBukuTamuEventIdRouteWithChildren
  '/dasbor/undangan/$id': typeof DasborUndanganIdRoute
  '/admin/aset/': typeof AdminAsetIndexRoute
  '/admin/deteksi-aset/': typeof AdminDeteksiAsetIndexRoute
  '/admin/doa/': typeof AdminDoaIndexRoute
  '/admin/galeri-aset/': typeof AdminGaleriAsetIndexRoute
  '/admin/musik/': typeof AdminMusikIndexRoute
  '/admin/pengguna/': typeof AdminPenggunaIndexRoute
  '/admin/promosi-template/': typeof AdminPromosiTemplateIndexRoute
  '/admin/quotes/': typeof AdminQuotesIndexRoute
  '/admin/surat/': typeof AdminSuratIndexRoute
  '/admin/template/': typeof AdminTemplateIndexRoute
  '/admin/undangan/': typeof AdminUndanganIndexRoute
  '/dasbor/buku-tamu/': typeof DasborBukuTamuIndexRoute
  '/dasbor/undangan/': typeof DasborUndanganIndexRoute
  '/admin/promosi-template/$id/aset': typeof AdminPromosiTemplateIdAsetRoute
  '/dasbor/buku-tamu/$eventId/analitik': typeof DasborBukuTamuEventIdAnalitikRoute
  '/dasbor/buku-tamu/$eventId/kehadiran': typeof DasborBukuTamuEventIdKehadiranRoute
  '/dasbor/buku-tamu/$eventId/log': typeof DasborBukuTamuEventIdLogRoute
  '/dasbor/buku-tamu/$eventId/pengaturan': typeof DasborBukuTamuEventIdPengaturanRoute
  '/dasbor/buku-tamu/$eventId/ucapan': typeof DasborBukuTamuEventIdUcapanRoute
  '/dasbor/buku-tamu/$eventId/': typeof DasborBukuTamuEventIdIndexRoute
  '/dasbor/buku-tamu/$eventId/tamu/$guestId': typeof DasborBukuTamuEventIdTamuGuestIdRoute
  '/dasbor/buku-tamu/$eventId/tamu/': typeof DasborBukuTamuEventIdTamuIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/fitur': typeof FiturRoute
  '/login': typeof LoginRoute
  '/masuk': typeof MasukRoute
  '/admin/arsitektur': typeof AdminArsitekturRoute
  '/admin/berita': typeof AdminBeritaRoute
  '/admin/paket': typeof AdminPaketRoute
  '/admin/pesan-wa': typeof AdminPesanWaRoute
  '/admin/profil': typeof AdminProfilRoute
  '/admin/promosi-gambar': typeof AdminPromosiGambarRoute
  '/admin/promosi-pengaturan': typeof AdminPromosiPengaturanRoute
  '/admin/promosi-video': typeof AdminPromosiVideoRoute
  '/admin/rsvp': typeof AdminRsvpRoute
  '/admin/sistem': typeof AdminSistemRoute
  '/admin/templates-ai': typeof AdminTemplatesAiRoute
  '/admin/transaksi': typeof AdminTransaksiRoute
  '/berita/$slug': typeof BeritaSlugRoute
  '/dasbor/acara': typeof DasborAcaraRoute
  '/dasbor/cerita': typeof DasborCeritaRoute
  '/dasbor/galeri': typeof DasborGaleriRoute
  '/dasbor/hadiah': typeof DasborHadiahRoute
  '/dasbor/mempelai': typeof DasborMempelaiRoute
  '/dasbor/paket': typeof DasborPaketRoute
  '/dasbor/pembelian': typeof DasborPembelianRoute
  '/dasbor/profil': typeof DasborProfilRoute
  '/dasbor/sebar': typeof DasborSebarRoute
  '/dasbor/tamu': typeof DasborTamuRoute
  '/dasbor/template': typeof DasborTemplateRoute
  '/demo-ai/$slug': typeof DemoAiSlugRoute
  '/demo/$slug': typeof DemoSlugRoute
  '/admin': typeof AdminIndexRoute
  '/berita': typeof BeritaIndexRoute
  '/dasbor': typeof DasborIndexRoute
  '/demo': typeof DemoIndexRoute
  '/admin/doa/$id': typeof AdminDoaIdRoute
  '/admin/doa/baru': typeof AdminDoaBaruRoute
  '/admin/galeri-aset/upload': typeof AdminGaleriAsetUploadRoute
  '/admin/musik/baru': typeof AdminMusikBaruRoute
  '/admin/pengguna/$id': typeof AdminPenggunaIdRoute
  '/admin/pengguna/baru': typeof AdminPenggunaBaruRoute
  '/admin/quotes/baru': typeof AdminQuotesBaruRoute
  '/admin/surat/baru': typeof AdminSuratBaruRoute
  '/admin/template/$id': typeof AdminTemplateIdRoute
  '/admin/template/upload': typeof AdminTemplateUploadRoute
  '/admin/undangan/$id': typeof AdminUndanganIdRoute
  '/admin/undangan/baru': typeof AdminUndanganBaruRoute
  '/dasbor/undangan/$id': typeof DasborUndanganIdRoute
  '/admin/aset': typeof AdminAsetIndexRoute
  '/admin/deteksi-aset': typeof AdminDeteksiAsetIndexRoute
  '/admin/doa': typeof AdminDoaIndexRoute
  '/admin/galeri-aset': typeof AdminGaleriAsetIndexRoute
  '/admin/musik': typeof AdminMusikIndexRoute
  '/admin/pengguna': typeof AdminPenggunaIndexRoute
  '/admin/promosi-template': typeof AdminPromosiTemplateIndexRoute
  '/admin/quotes': typeof AdminQuotesIndexRoute
  '/admin/surat': typeof AdminSuratIndexRoute
  '/admin/template': typeof AdminTemplateIndexRoute
  '/admin/undangan': typeof AdminUndanganIndexRoute
  '/dasbor/buku-tamu': typeof DasborBukuTamuIndexRoute
  '/dasbor/undangan': typeof DasborUndanganIndexRoute
  '/admin/promosi-template/$id/aset': typeof AdminPromosiTemplateIdAsetRoute
  '/dasbor/buku-tamu/$eventId/analitik': typeof DasborBukuTamuEventIdAnalitikRoute
  '/dasbor/buku-tamu/$eventId/kehadiran': typeof DasborBukuTamuEventIdKehadiranRoute
  '/dasbor/buku-tamu/$eventId/log': typeof DasborBukuTamuEventIdLogRoute
  '/dasbor/buku-tamu/$eventId/pengaturan': typeof DasborBukuTamuEventIdPengaturanRoute
  '/dasbor/buku-tamu/$eventId/ucapan': typeof DasborBukuTamuEventIdUcapanRoute
  '/dasbor/buku-tamu/$eventId': typeof DasborBukuTamuEventIdIndexRoute
  '/dasbor/buku-tamu/$eventId/tamu/$guestId': typeof DasborBukuTamuEventIdTamuGuestIdRoute
  '/dasbor/buku-tamu/$eventId/tamu': typeof DasborBukuTamuEventIdTamuIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/admin': typeof AdminRouteWithChildren
  '/dasbor': typeof DasborRouteWithChildren
  '/fitur': typeof FiturRoute
  '/login': typeof LoginRoute
  '/masuk': typeof MasukRoute
  '/admin/arsitektur': typeof AdminArsitekturRoute
  '/admin/berita': typeof AdminBeritaRoute
  '/admin/paket': typeof AdminPaketRoute
  '/admin/pesan-wa': typeof AdminPesanWaRoute
  '/admin/profil': typeof AdminProfilRoute
  '/admin/promosi-gambar': typeof AdminPromosiGambarRoute
  '/admin/promosi-pengaturan': typeof AdminPromosiPengaturanRoute
  '/admin/promosi-video': typeof AdminPromosiVideoRoute
  '/admin/rsvp': typeof AdminRsvpRoute
  '/admin/sistem': typeof AdminSistemRoute
  '/admin/templates-ai': typeof AdminTemplatesAiRoute
  '/admin/transaksi': typeof AdminTransaksiRoute
  '/berita/$slug': typeof BeritaSlugRoute
  '/dasbor/acara': typeof DasborAcaraRoute
  '/dasbor/cerita': typeof DasborCeritaRoute
  '/dasbor/galeri': typeof DasborGaleriRoute
  '/dasbor/hadiah': typeof DasborHadiahRoute
  '/dasbor/mempelai': typeof DasborMempelaiRoute
  '/dasbor/paket': typeof DasborPaketRoute
  '/dasbor/pembelian': typeof DasborPembelianRoute
  '/dasbor/profil': typeof DasborProfilRoute
  '/dasbor/sebar': typeof DasborSebarRoute
  '/dasbor/tamu': typeof DasborTamuRoute
  '/dasbor/template': typeof DasborTemplateRoute
  '/demo-ai/$slug': typeof DemoAiSlugRoute
  '/demo/$slug': typeof DemoSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/berita/': typeof BeritaIndexRoute
  '/dasbor/': typeof DasborIndexRoute
  '/demo/': typeof DemoIndexRoute
  '/admin/doa/$id': typeof AdminDoaIdRoute
  '/admin/doa/baru': typeof AdminDoaBaruRoute
  '/admin/galeri-aset/upload': typeof AdminGaleriAsetUploadRoute
  '/admin/musik/baru': typeof AdminMusikBaruRoute
  '/admin/pengguna/$id': typeof AdminPenggunaIdRoute
  '/admin/pengguna/baru': typeof AdminPenggunaBaruRoute
  '/admin/quotes/baru': typeof AdminQuotesBaruRoute
  '/admin/surat/baru': typeof AdminSuratBaruRoute
  '/admin/template/$id': typeof AdminTemplateIdRoute
  '/admin/template/upload': typeof AdminTemplateUploadRoute
  '/admin/undangan/$id': typeof AdminUndanganIdRoute
  '/admin/undangan/baru': typeof AdminUndanganBaruRoute
  '/dasbor/buku-tamu/$eventId': typeof DasborBukuTamuEventIdRouteWithChildren
  '/dasbor/undangan/$id': typeof DasborUndanganIdRoute
  '/admin/aset/': typeof AdminAsetIndexRoute
  '/admin/deteksi-aset/': typeof AdminDeteksiAsetIndexRoute
  '/admin/doa/': typeof AdminDoaIndexRoute
  '/admin/galeri-aset/': typeof AdminGaleriAsetIndexRoute
  '/admin/musik/': typeof AdminMusikIndexRoute
  '/admin/pengguna/': typeof AdminPenggunaIndexRoute
  '/admin/promosi-template/': typeof AdminPromosiTemplateIndexRoute
  '/admin/quotes/': typeof AdminQuotesIndexRoute
  '/admin/surat/': typeof AdminSuratIndexRoute
  '/admin/template/': typeof AdminTemplateIndexRoute
  '/admin/undangan/': typeof AdminUndanganIndexRoute
  '/dasbor/buku-tamu/': typeof DasborBukuTamuIndexRoute
  '/dasbor/undangan/': typeof DasborUndanganIndexRoute
  '/admin/promosi-template/$id/aset': typeof AdminPromosiTemplateIdAsetRoute
  '/dasbor/buku-tamu/$eventId/analitik': typeof DasborBukuTamuEventIdAnalitikRoute
  '/dasbor/buku-tamu/$eventId/kehadiran': typeof DasborBukuTamuEventIdKehadiranRoute
  '/dasbor/buku-tamu/$eventId/log': typeof DasborBukuTamuEventIdLogRoute
  '/dasbor/buku-tamu/$eventId/pengaturan': typeof DasborBukuTamuEventIdPengaturanRoute
  '/dasbor/buku-tamu/$eventId/ucapan': typeof DasborBukuTamuEventIdUcapanRoute
  '/dasbor/buku-tamu/$eventId/': typeof DasborBukuTamuEventIdIndexRoute
  '/dasbor/buku-tamu/$eventId/tamu/$guestId': typeof DasborBukuTamuEventIdTamuGuestIdRoute
  '/dasbor/buku-tamu/$eventId/tamu/': typeof DasborBukuTamuEventIdTamuIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/admin'
    | '/dasbor'
    | '/fitur'
    | '/login'
    | '/masuk'
    | '/admin/arsitektur'
    | '/admin/berita'
    | '/admin/paket'
    | '/admin/pesan-wa'
    | '/admin/profil'
    | '/admin/promosi-gambar'
    | '/admin/promosi-pengaturan'
    | '/admin/promosi-video'
    | '/admin/rsvp'
    | '/admin/sistem'
    | '/admin/templates-ai'
    | '/admin/transaksi'
    | '/berita/$slug'
    | '/dasbor/acara'
    | '/dasbor/cerita'
    | '/dasbor/galeri'
    | '/dasbor/hadiah'
    | '/dasbor/mempelai'
    | '/dasbor/paket'
    | '/dasbor/pembelian'
    | '/dasbor/profil'
    | '/dasbor/sebar'
    | '/dasbor/tamu'
    | '/dasbor/template'
    | '/demo-ai/$slug'
    | '/demo/$slug'
    | '/admin/'
    | '/berita/'
    | '/dasbor/'
    | '/demo/'
    | '/admin/doa/$id'
    | '/admin/doa/baru'
    | '/admin/galeri-aset/upload'
    | '/admin/musik/baru'
    | '/admin/pengguna/$id'
    | '/admin/pengguna/baru'
    | '/admin/quotes/baru'
    | '/admin/surat/baru'
    | '/admin/template/$id'
    | '/admin/template/upload'
    | '/admin/undangan/$id'
    | '/admin/undangan/baru'
    | '/dasbor/buku-tamu/$eventId'
    | '/dasbor/undangan/$id'
    | '/admin/aset/'
    | '/admin/deteksi-aset/'
    | '/admin/doa/'
    | '/admin/galeri-aset/'
    | '/admin/musik/'
    | '/admin/pengguna/'
    | '/admin/promosi-template/'
    | '/admin/quotes/'
    | '/admin/surat/'
    | '/admin/template/'
    | '/admin/undangan/'
    | '/dasbor/buku-tamu/'
    | '/dasbor/undangan/'
    | '/admin/promosi-template/$id/aset'
    | '/dasbor/buku-tamu/$eventId/analitik'
    | '/dasbor/buku-tamu/$eventId/kehadiran'
    | '/dasbor/buku-tamu/$eventId/log'
    | '/dasbor/buku-tamu/$eventId/pengaturan'
    | '/dasbor/buku-tamu/$eventId/ucapan'
    | '/dasbor/buku-tamu/$eventId/'
    | '/dasbor/buku-tamu/$eventId/tamu/$guestId'
    | '/dasbor/buku-tamu/$eventId/tamu/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/fitur'
    | '/login'
    | '/masuk'
    | '/admin/arsitektur'
    | '/admin/berita'
    | '/admin/paket'
    | '/admin/pesan-wa'
    | '/admin/profil'
    | '/admin/promosi-gambar'
    | '/admin/promosi-pengaturan'
    | '/admin/promosi-video'
    | '/admin/rsvp'
    | '/admin/sistem'
    | '/admin/templates-ai'
    | '/admin/transaksi'
    | '/berita/$slug'
    | '/dasbor/acara'
    | '/dasbor/cerita'
    | '/dasbor/galeri'
    | '/dasbor/hadiah'
    | '/dasbor/mempelai'
    | '/dasbor/paket'
    | '/dasbor/pembelian'
    | '/dasbor/profil'
    | '/dasbor/sebar'
    | '/dasbor/tamu'
    | '/dasbor/template'
    | '/demo-ai/$slug'
    | '/demo/$slug'
    | '/admin'
    | '/berita'
    | '/dasbor'
    | '/demo'
    | '/admin/doa/$id'
    | '/admin/doa/baru'
    | '/admin/galeri-aset/upload'
    | '/admin/musik/baru'
    | '/admin/pengguna/$id'
    | '/admin/pengguna/baru'
    | '/admin/quotes/baru'
    | '/admin/surat/baru'
    | '/admin/template/$id'
    | '/admin/template/upload'
    | '/admin/undangan/$id'
    | '/admin/undangan/baru'
    | '/dasbor/undangan/$id'
    | '/admin/aset'
    | '/admin/deteksi-aset'
    | '/admin/doa'
    | '/admin/galeri-aset'
    | '/admin/musik'
    | '/admin/pengguna'
    | '/admin/promosi-template'
    | '/admin/quotes'
    | '/admin/surat'
    | '/admin/template'
    | '/admin/undangan'
    | '/dasbor/buku-tamu'
    | '/dasbor/undangan'
    | '/admin/promosi-template/$id/aset'
    | '/dasbor/buku-tamu/$eventId/analitik'
    | '/dasbor/buku-tamu/$eventId/kehadiran'
    | '/dasbor/buku-tamu/$eventId/log'
    | '/dasbor/buku-tamu/$eventId/pengaturan'
    | '/dasbor/buku-tamu/$eventId/ucapan'
    | '/dasbor/buku-tamu/$eventId'
    | '/dasbor/buku-tamu/$eventId/tamu/$guestId'
    | '/dasbor/buku-tamu/$eventId/tamu'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/admin'
    | '/dasbor'
    | '/fitur'
    | '/login'
    | '/masuk'
    | '/admin/arsitektur'
    | '/admin/berita'
    | '/admin/paket'
    | '/admin/pesan-wa'
    | '/admin/profil'
    | '/admin/promosi-gambar'
    | '/admin/promosi-pengaturan'
    | '/admin/promosi-video'
    | '/admin/rsvp'
    | '/admin/sistem'
    | '/admin/templates-ai'
    | '/admin/transaksi'
    | '/berita/$slug'
    | '/dasbor/acara'
    | '/dasbor/cerita'
    | '/dasbor/galeri'
    | '/dasbor/hadiah'
    | '/dasbor/mempelai'
    | '/dasbor/paket'
    | '/dasbor/pembelian'
    | '/dasbor/profil'
    | '/dasbor/sebar'
    | '/dasbor/tamu'
    | '/dasbor/template'
    | '/demo-ai/$slug'
    | '/demo/$slug'
    | '/admin/'
    | '/berita/'
    | '/dasbor/'
    | '/demo/'
    | '/admin/doa/$id'
    | '/admin/doa/baru'
    | '/admin/galeri-aset/upload'
    | '/admin/musik/baru'
    | '/admin/pengguna/$id'
    | '/admin/pengguna/baru'
    | '/admin/quotes/baru'
    | '/admin/surat/baru'
    | '/admin/template/$id'
    | '/admin/template/upload'
    | '/admin/undangan/$id'
    | '/admin/undangan/baru'
    | '/dasbor/buku-tamu/$eventId'
    | '/dasbor/undangan/$id'
    | '/admin/aset/'
    | '/admin/deteksi-aset/'
    | '/admin/doa/'
    | '/admin/galeri-aset/'
    | '/admin/musik/'
    | '/admin/pengguna/'
    | '/admin/promosi-template/'
    | '/admin/quotes/'
    | '/admin/surat/'
    | '/admin/template/'
    | '/admin/undangan/'
    | '/dasbor/buku-tamu/'
    | '/dasbor/undangan/'
    | '/admin/promosi-template/$id/aset'
    | '/dasbor/buku-tamu/$eventId/analitik'
    | '/dasbor/buku-tamu/$eventId/kehadiran'
    | '/dasbor/buku-tamu/$eventId/log'
    | '/dasbor/buku-tamu/$eventId/pengaturan'
    | '/dasbor/buku-tamu/$eventId/ucapan'
    | '/dasbor/buku-tamu/$eventId/'
    | '/dasbor/buku-tamu/$eventId/tamu/$guestId'
    | '/dasbor/buku-tamu/$eventId/tamu/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  AdminRoute: typeof AdminRouteWithChildren
  DasborRoute: typeof DasborRouteWithChildren
  FiturRoute: typeof FiturRoute
  LoginRoute: typeof LoginRoute
  MasukRoute: typeof MasukRoute
  BeritaSlugRoute: typeof BeritaSlugRoute
  DemoAiSlugRoute: typeof DemoAiSlugRoute
  DemoSlugRoute: typeof DemoSlugRoute
  BeritaIndexRoute: typeof BeritaIndexRoute
  DemoIndexRoute: typeof DemoIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dasbor': {
      id: '/dasbor'
      path: '/dasbor'
      fullPath: '/dasbor'
      preLoaderRoute: typeof DasborRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fitur': {
      id: '/fitur'
      path: '/fitur'
      fullPath: '/fitur'
      preLoaderRoute: typeof FiturRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/masuk': {
      id: '/masuk'
      path: '/masuk'
      fullPath: '/masuk'
      preLoaderRoute: typeof MasukRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/arsitektur': {
      id: '/admin/arsitektur'
      path: '/arsitektur'
      fullPath: '/admin/arsitektur'
      preLoaderRoute: typeof AdminArsitekturRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/berita': {
      id: '/admin/berita'
      path: '/berita'
      fullPath: '/admin/berita'
      preLoaderRoute: typeof AdminBeritaRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/paket': {
      id: '/admin/paket'
      path: '/paket'
      fullPath: '/admin/paket'
      preLoaderRoute: typeof AdminPaketRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/pesan-wa': {
      id: '/admin/pesan-wa'
      path: '/pesan-wa'
      fullPath: '/admin/pesan-wa'
      preLoaderRoute: typeof AdminPesanWaRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/profil': {
      id: '/admin/profil'
      path: '/profil'
      fullPath: '/admin/profil'
      preLoaderRoute: typeof AdminProfilRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/promosi-gambar': {
      id: '/admin/promosi-gambar'
      path: '/promosi-gambar'
      fullPath: '/admin/promosi-gambar'
      preLoaderRoute: typeof AdminPromosiGambarRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/promosi-pengaturan': {
      id: '/admin/promosi-pengaturan'
      path: '/promosi-pengaturan'
      fullPath: '/admin/promosi-pengaturan'
      preLoaderRoute: typeof AdminPromosiPengaturanRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/promosi-video': {
      id: '/admin/promosi-video'
      path: '/promosi-video'
      fullPath: '/admin/promosi-video'
      preLoaderRoute: typeof AdminPromosiVideoRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/rsvp': {
      id: '/admin/rsvp'
      path: '/rsvp'
      fullPath: '/admin/rsvp'
      preLoaderRoute: typeof AdminRsvpRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/sistem': {
      id: '/admin/sistem'
      path: '/sistem'
      fullPath: '/admin/sistem'
      preLoaderRoute: typeof AdminSistemRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/templates-ai': {
      id: '/admin/templates-ai'
      path: '/templates-ai'
      fullPath: '/admin/templates-ai'
      preLoaderRoute: typeof AdminTemplatesAiRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/transaksi': {
      id: '/admin/transaksi'
      path: '/transaksi'
      fullPath: '/admin/transaksi'
      preLoaderRoute: typeof AdminTransaksiRouteImport
      parentRoute: typeof AdminRoute
    }
    '/berita/': {
      id: '/berita/'
      path: '/berita'
      fullPath: '/berita/'
      preLoaderRoute: typeof BeritaIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/berita/$slug': {
      id: '/berita/$slug'
      path: '/berita/$slug'
      fullPath: '/berita/$slug'
      preLoaderRoute: typeof BeritaSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dasbor/': {
      id: '/dasbor/'
      path: '/'
      fullPath: '/dasbor/'
      preLoaderRoute: typeof DasborIndexRouteImport
      parentRoute: typeof DasborRoute
    }
    '/dasbor/acara': {
      id: '/dasbor/acara'
      path: '/acara'
      fullPath: '/dasbor/acara'
      preLoaderRoute: typeof DasborAcaraRouteImport
      parentRoute: typeof DasborRoute
    }
    '/dasbor/cerita': {
      id: '/dasbor/cerita'
      path: '/cerita'
      fullPath: '/dasbor/cerita'
      preLoaderRoute: typeof DasborCeritaRouteImport
      parentRoute: typeof DasborRoute
    }
    '/dasbor/galeri': {
      id: '/dasbor/galeri'
      path: '/galeri'
      fullPath: '/dasbor/galeri'
      preLoaderRoute: typeof DasborGaleriRouteImport
      parentRoute: typeof DasborRoute
    }
    '/dasbor/hadiah': {
      id: '/dasbor/hadiah'
      path: '/hadiah'
      fullPath: '/dasbor/hadiah'
      preLoaderRoute: typeof DasborHadiahRouteImport
      parentRoute: typeof DasborRoute
    }
    '/dasbor/mempelai': {
      id: '/dasbor/mempelai'
      path: '/mempelai'
      fullPath: '/dasbor/mempelai'
      preLoaderRoute: typeof DasborMempelaiRouteImport
      parentRoute: typeof DasborRoute
    }
    '/dasbor/paket': {
      id: '/dasbor/paket'
      path: '/paket'
      fullPath: '/dasbor/paket'
      preLoaderRoute: typeof DasborPaketRouteImport
      parentRoute: typeof DasborRoute
    }
    '/dasbor/pembelian': {
      id: '/dasbor/pembelian'
      path: '/pembelian'
      fullPath: '/dasbor/pembelian'
      preLoaderRoute: typeof DasborPembelianRouteImport
      parentRoute: typeof DasborRoute
    }
    '/dasbor/profil': {
      id: '/dasbor/profil'
      path: '/profil'
      fullPath: '/dasbor/profil'
      preLoaderRoute: typeof DasborProfilRouteImport
      parentRoute: typeof DasborRoute
    }
    '/dasbor/sebar': {
      id: '/dasbor/sebar'
      path: '/sebar'
      fullPath: '/dasbor/sebar'
      preLoaderRoute: typeof DasborSebarRouteImport
      parentRoute: typeof DasborRoute
    }
    '/dasbor/tamu': {
      id: '/dasbor/tamu'
      path: '/tamu'
      fullPath: '/dasbor/tamu'
      preLoaderRoute: typeof DasborTamuRouteImport
      parentRoute: typeof DasborRoute
    }
    '/dasbor/template': {
      id: '/dasbor/template'
      path: '/template'
      fullPath: '/dasbor/template'
      preLoaderRoute: typeof DasborTemplateRouteImport
      parentRoute: typeof DasborRoute
    }
    '/demo-ai/$slug': {
      id: '/demo-ai/$slug'
      path: '/demo-ai/$slug'
      fullPath: '/demo-ai/$slug'
      preLoaderRoute: typeof DemoAiSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/': {
      id: '/demo/'
      path: '/demo'
      fullPath: '/demo/'
      preLoaderRoute: typeof DemoIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/$slug': {
      id: '/demo/$slug'
      path: '/demo/$slug'
      fullPath: '/demo/$slug'
      preLoaderRoute: typeof DemoSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/aset/': {
      id: '/admin/aset/'
      path: '/aset'
      fullPath: '/admin/aset/'
      preLoaderRoute: typeof AdminAsetIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/deteksi-aset/': {
      id: '/admin/deteksi-aset/'
      path: '/deteksi-aset'
      fullPath: '/admin/deteksi-aset/'
      preLoaderRoute: typeof AdminDeteksiAsetIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/doa/': {
      id: '/admin/doa/'
      path: '/doa'
      fullPath: '/admin/doa/'
      preLoaderRoute: typeof AdminDoaIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/doa/$id': {
      id: '/admin/doa/$id'
      path: '/doa/$id'
      fullPath: '/admin/doa/$id'
      preLoaderRoute: typeof AdminDoaIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/doa/baru': {
      id: '/admin/doa/baru'
      path: '/doa/baru'
      fullPath: '/admin/doa/baru'
      preLoaderRoute: typeof AdminDoaBaruRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/galeri-aset/': {
      id: '/admin/galeri-aset/'
      path: '/galeri-aset'
      fullPath: '/admin/galeri-aset/'
      preLoaderRoute: typeof AdminGaleriAsetIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/galeri-aset/upload': {
      id: '/admin/galeri-aset/upload'
      path: '/galeri-aset/upload'
      fullPath: '/admin/galeri-aset/upload'
      preLoaderRoute: typeof AdminGaleriAsetUploadRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/musik/': {
      id: '/admin/musik/'
      path: '/musik'
      fullPath: '/admin/musik/'
      preLoaderRoute: typeof AdminMusikIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/musik/baru': {
      id: '/admin/musik/baru'
      path: '/musik/baru'
      fullPath: '/admin/musik/baru'
      preLoaderRoute: typeof AdminMusikBaruRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/pengguna/': {
      id: '/admin/pengguna/'
      path: '/pengguna'
      fullPath: '/admin/pengguna/'
      preLoaderRoute: typeof AdminPenggunaIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/pengguna/$id': {
      id: '/admin/pengguna/$id'
      path: '/pengguna/$id'
      fullPath: '/admin/pengguna/$id'
      preLoaderRoute: typeof AdminPenggunaIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/pengguna/baru': {
      id: '/admin/pengguna/baru'
      path: '/pengguna/baru'
      fullPath: '/admin/pengguna/baru'
      preLoaderRoute: typeof AdminPenggunaBaruRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/promosi-template/': {
      id: '/admin/promosi-template/'
      path: '/promosi-template'
      fullPath: '/admin/promosi-template/'
      preLoaderRoute: typeof AdminPromosiTemplateIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/quotes/': {
      id: '/admin/quotes/'
      path: '/quotes'
      fullPath: '/admin/quotes/'
      preLoaderRoute: typeof AdminQuotesIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/quotes/baru': {
      id: '/admin/quotes/baru'
      path: '/quotes/baru'
      fullPath: '/admin/quotes/baru'
      preLoaderRoute: typeof AdminQuotesBaruRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/surat/': {
      id: '/admin/surat/'
      path: '/surat'
      fullPath: '/admin/surat/'
      preLoaderRoute: typeof AdminSuratIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/surat/baru': {
      id: '/admin/surat/baru'
      path: '/surat/baru'
      fullPath: '/admin/surat/baru'
      preLoaderRoute: typeof AdminSuratBaruRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/template/': {
      id: '/admin/template/'
      path: '/template'
      fullPath: '/admin/template/'
      preLoaderRoute: typeof AdminTemplateIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/template/$id': {
      id: '/admin/template/$id'
      path: '/template/$id'
      fullPath: '/admin/template/$id'
      preLoaderRoute: typeof AdminTemplateIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/template/upload': {
      id: '/admin/template/upload'
      path: '/template/upload'
      fullPath: '/admin/template/upload'
      preLoaderRoute: typeof AdminTemplateUploadRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/undangan/': {
      id: '/admin/undangan/'
      path: '/undangan'
      fullPath: '/admin/undangan/'
      preLoaderRoute: typeof AdminUndanganIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/undangan/$id': {
      id: '/admin/undangan/$id'
      path: '/undangan/$id'
      fullPath: '/admin/undangan/$id'
      preLoaderRoute: typeof AdminUndanganIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/undangan/baru': {
      id: '/admin/undangan/baru'
      path: '/undangan/baru'
      fullPath: '/admin/undangan/baru'
      preLoaderRoute: typeof AdminUndanganBaruRouteImport
      parentRoute: typeof AdminRoute
    }
    '/dasbor/buku-tamu/': {
      id: '/dasbor/buku-tamu/'
      path: '/buku-tamu'
      fullPath: '/dasbor/buku-tamu/'
      preLoaderRoute: typeof DasborBukuTamuIndexRouteImport
      parentRoute: typeof DasborRoute
    }
    '/dasbor/buku-tamu/$eventId': {
      id: '/dasbor/buku-tamu/$eventId'
      path: '/buku-tamu/$eventId'
      fullPath: '/dasbor/buku-tamu/$eventId'
      preLoaderRoute: typeof DasborBukuTamuEventIdRouteImport
      parentRoute: typeof DasborRoute
    }
    '/dasbor/undangan/': {
      id: '/dasbor/undangan/'
      path: '/undangan'
      fullPath: '/dasbor/undangan/'
      preLoaderRoute: typeof DasborUndanganIndexRouteImport
      parentRoute: typeof DasborRoute
    }
    '/dasbor/undangan/$id': {
      id: '/dasbor/undangan/$id'
      path: '/undangan/$id'
      fullPath: '/dasbor/undangan/$id'
      preLoaderRoute: typeof DasborUndanganIdRouteImport
      parentRoute: typeof DasborRoute
    }
    '/admin/promosi-template/$id/aset': {
      id: '/admin/promosi-template/$id/aset'
      path: '/promosi-template/$id/aset'
      fullPath: '/admin/promosi-template/$id/aset'
      preLoaderRoute: typeof AdminPromosiTemplateIdAsetRouteImport
      parentRoute: typeof AdminRoute
    }
    '/dasbor/buku-tamu/$eventId/': {
      id: '/dasbor/buku-tamu/$eventId/'
      path: '/'
      fullPath: '/dasbor/buku-tamu/$eventId/'
      preLoaderRoute: typeof DasborBukuTamuEventIdIndexRouteImport
      parentRoute: typeof DasborBukuTamuEventIdRoute
    }
    '/dasbor/buku-tamu/$eventId/analitik': {
      id: '/dasbor/buku-tamu/$eventId/analitik'
      path: '/analitik'
      fullPath: '/dasbor/buku-tamu/$eventId/analitik'
      preLoaderRoute: typeof DasborBukuTamuEventIdAnalitikRouteImport
      parentRoute: typeof DasborBukuTamuEventIdRoute
    }
    '/dasbor/buku-tamu/$eventId/kehadiran': {
      id: '/dasbor/buku-tamu/$eventId/kehadiran'
      path: '/kehadiran'
      fullPath: '/dasbor/buku-tamu/$eventId/kehadiran'
      preLoaderRoute: typeof DasborBukuTamuEventIdKehadiranRouteImport
      parentRoute: typeof DasborBukuTamuEventIdRoute
    }
    '/dasbor/buku-tamu/$eventId/log': {
      id: '/dasbor/buku-tamu/$eventId/log'
      path: '/log'
      fullPath: '/dasbor/buku-tamu/$eventId/log'
      preLoaderRoute: typeof DasborBukuTamuEventIdLogRouteImport
      parentRoute: typeof DasborBukuTamuEventIdRoute
    }
    '/dasbor/buku-tamu/$eventId/pengaturan': {
      id: '/dasbor/buku-tamu/$eventId/pengaturan'
      path: '/pengaturan'
      fullPath: '/dasbor/buku-tamu/$eventId/pengaturan'
      preLoaderRoute: typeof DasborBukuTamuEventIdPengaturanRouteImport
      parentRoute: typeof DasborBukuTamuEventIdRoute
    }
    '/dasbor/buku-tamu/$eventId/ucapan': {
      id: '/dasbor/buku-tamu/$eventId/ucapan'
      path: '/ucapan'
      fullPath: '/dasbor/buku-tamu/$eventId/ucapan'
      preLoaderRoute: typeof DasborBukuTamuEventIdUcapanRouteImport
      parentRoute: typeof DasborBukuTamuEventIdRoute
    }
    '/dasbor/buku-tamu/$eventId/tamu/': {
      id: '/dasbor/buku-tamu/$eventId/tamu/'
      path: '/tamu'
      fullPath: '/dasbor/buku-tamu/$eventId/tamu/'
      preLoaderRoute: typeof DasborBukuTamuEventIdTamuIndexRouteImport
      parentRoute: typeof DasborBukuTamuEventIdRoute
    }
    '/dasbor/buku-tamu/$eventId/tamu/$guestId': {
      id: '/dasbor/buku-tamu/$eventId/tamu/$guestId'
      path: '/tamu/$guestId'
      fullPath: '/dasbor/buku-tamu/$eventId/tamu/$guestId'
      preLoaderRoute: typeof DasborBukuTamuEventIdTamuGuestIdRouteImport
      parentRoute: typeof DasborBukuTamuEventIdRoute
    }
  }
}

interface AdminRouteChildren {
  AdminArsitekturRoute: typeof AdminArsitekturRoute
  AdminBeritaRoute: typeof AdminBeritaRoute
  AdminPaketRoute: typeof AdminPaketRoute
  AdminPesanWaRoute: typeof AdminPesanWaRoute
  AdminProfilRoute: typeof AdminProfilRoute
  AdminPromosiGambarRoute: typeof AdminPromosiGambarRoute
  AdminPromosiPengaturanRoute: typeof AdminPromosiPengaturanRoute
  AdminPromosiVideoRoute: typeof AdminPromosiVideoRoute
  AdminRsvpRoute: typeof AdminRsvpRoute
  AdminSistemRoute: typeof AdminSistemRoute
  AdminTemplatesAiRoute: typeof AdminTemplatesAiRoute
  AdminTransaksiRoute: typeof AdminTransaksiRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminDoaIdRoute: typeof AdminDoaIdRoute
  AdminDoaBaruRoute: typeof AdminDoaBaruRoute
  AdminGaleriAsetUploadRoute: typeof AdminGaleriAsetUploadRoute
  AdminMusikBaruRoute: typeof AdminMusikBaruRoute
  AdminPenggunaIdRoute: typeof AdminPenggunaIdRoute
  AdminPenggunaBaruRoute: typeof AdminPenggunaBaruRoute
  AdminQuotesBaruRoute: typeof AdminQuotesBaruRoute
  AdminSuratBaruRoute: typeof AdminSuratBaruRoute
  AdminTemplateIdRoute: typeof AdminTemplateIdRoute
  AdminTemplateUploadRoute: typeof AdminTemplateUploadRoute
  AdminUndanganIdRoute: typeof AdminUndanganIdRoute
  AdminUndanganBaruRoute: typeof AdminUndanganBaruRoute
  AdminAsetIndexRoute: typeof AdminAsetIndexRoute
  AdminDeteksiAsetIndexRoute: typeof AdminDeteksiAsetIndexRoute
  AdminDoaIndexRoute: typeof AdminDoaIndexRoute
  AdminGaleriAsetIndexRoute: typeof AdminGaleriAsetIndexRoute
  AdminMusikIndexRoute: typeof AdminMusikIndexRoute
  AdminPenggunaIndexRoute: typeof AdminPenggunaIndexRoute
  AdminPromosiTemplateIndexRoute: typeof AdminPromosiTemplateIndexRoute
  AdminQuotesIndexRoute: typeof AdminQuotesIndexRoute
  AdminSuratIndexRoute: typeof AdminSuratIndexRoute
  AdminTemplateIndexRoute: typeof AdminTemplateIndexRoute
  AdminUndanganIndexRoute: typeof AdminUndanganIndexRoute
  AdminPromosiTemplateIdAsetRoute: typeof AdminPromosiTemplateIdAsetRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminArsitekturRoute: AdminArsitekturRoute,
  AdminBeritaRoute: AdminBeritaRoute,
  AdminPaketRoute: AdminPaketRoute,
  AdminPesanWaRoute: AdminPesanWaRoute,
  AdminProfilRoute: AdminProfilRoute,
  AdminPromosiGambarRoute: AdminPromosiGambarRoute,
  AdminPromosiPengaturanRoute: AdminPromosiPengaturanRoute,
  AdminPromosiVideoRoute: AdminPromosiVideoRoute,
  AdminRsvpRoute: AdminRsvpRoute,
  AdminSistemRoute: AdminSistemRoute,
  AdminTemplatesAiRoute: AdminTemplatesAiRoute,
  AdminTransaksiRoute: AdminTransaksiRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminDoaIdRoute: AdminDoaIdRoute,
  AdminDoaBaruRoute: AdminDoaBaruRoute,
  AdminGaleriAsetUploadRoute: AdminGaleriAsetUploadRoute,
  AdminMusikBaruRoute: AdminMusikBaruRoute,
  AdminPenggunaIdRoute: AdminPenggunaIdRoute,
  AdminPenggunaBaruRoute: AdminPenggunaBaruRoute,
  AdminQuotesBaruRoute: AdminQuotesBaruRoute,
  AdminSuratBaruRoute: AdminSuratBaruRoute,
  AdminTemplateIdRoute: AdminTemplateIdRoute,
  AdminTemplateUploadRoute: AdminTemplateUploadRoute,
  AdminUndanganIdRoute: AdminUndanganIdRoute,
  AdminUndanganBaruRoute: AdminUndanganBaruRoute,
  AdminAsetIndexRoute: AdminAsetIndexRoute,
  AdminDeteksiAsetIndexRoute: AdminDeteksiAsetIndexRoute,
  AdminDoaIndexRoute: AdminDoaIndexRoute,
  AdminGaleriAsetIndexRoute: AdminGaleriAsetIndexRoute,
  AdminMusikIndexRoute: AdminMusikIndexRoute,
  AdminPenggunaIndexRoute: AdminPenggunaIndexRoute,
  AdminPromosiTemplateIndexRoute: AdminPromosiTemplateIndexRoute,
  AdminQuotesIndexRoute: AdminQuotesIndexRoute,
  AdminSuratIndexRoute: AdminSuratIndexRoute,
  AdminTemplateIndexRoute: AdminTemplateIndexRoute,
  AdminUndanganIndexRoute: AdminUndanganIndexRoute,
  AdminPromosiTemplateIdAsetRoute: AdminPromosiTemplateIdAsetRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface DasborBukuTamuEventIdRouteChildren {
  DasborBukuTamuEventIdAnalitikRoute: typeof DasborBukuTamuEventIdAnalitikRoute
  DasborBukuTamuEventIdKehadiranRoute: typeof DasborBukuTamuEventIdKehadiranRoute
  DasborBukuTamuEventIdLogRoute: typeof DasborBukuTamuEventIdLogRoute
  DasborBukuTamuEventIdPengaturanRoute: typeof DasborBukuTamuEventIdPengaturanRoute
  DasborBukuTamuEventIdUcapanRoute: typeof DasborBukuTamuEventIdUcapanRoute
  DasborBukuTamuEventIdIndexRoute: typeof DasborBukuTamuEventIdIndexRoute
  DasborBukuTamuEventIdTamuGuestIdRoute: typeof DasborBukuTamuEventIdTamuGuestIdRoute
  DasborBukuTamuEventIdTamuIndexRoute: typeof DasborBukuTamuEventIdTamuIndexRoute
}

const DasborBukuTamuEventIdRouteChildren: DasborBukuTamuEventIdRouteChildren = {
  DasborBukuTamuEventIdAnalitikRoute: DasborBukuTamuEventIdAnalitikRoute,
  DasborBukuTamuEventIdKehadiranRoute: DasborBukuTamuEventIdKehadiranRoute,
  DasborBukuTamuEventIdLogRoute: DasborBukuTamuEventIdLogRoute,
  DasborBukuTamuEventIdPengaturanRoute: DasborBukuTamuEventIdPengaturanRoute,
  DasborBukuTamuEventIdUcapanRoute: DasborBukuTamuEventIdUcapanRoute,
  DasborBukuTamuEventIdIndexRoute: DasborBukuTamuEventIdIndexRoute,
  DasborBukuTamuEventIdTamuGuestIdRoute: DasborBukuTamuEventIdTamuGuestIdRoute,
  DasborBukuTamuEventIdTamuIndexRoute: DasborBukuTamuEventIdTamuIndexRoute,
}

const DasborBukuTamuEventIdRouteWithChildren =
  DasborBukuTamuEventIdRoute._addFileChildren(
    DasborBukuTamuEventIdRouteChildren,
  )

interface DasborRouteChildren {
  DasborAcaraRoute: typeof DasborAcaraRoute
  DasborCeritaRoute: typeof DasborCeritaRoute
  DasborGaleriRoute: typeof DasborGaleriRoute
  DasborHadiahRoute: typeof DasborHadiahRoute
  DasborMempelaiRoute: typeof DasborMempelaiRoute
  DasborPaketRoute: typeof DasborPaketRoute
  DasborPembelianRoute: typeof DasborPembelianRoute
  DasborProfilRoute: typeof DasborProfilRoute
  DasborSebarRoute: typeof DasborSebarRoute
  DasborTamuRoute: typeof DasborTamuRoute
  DasborTemplateRoute: typeof DasborTemplateRoute
  DasborIndexRoute: typeof DasborIndexRoute
  DasborBukuTamuEventIdRoute: typeof DasborBukuTamuEventIdRouteWithChildren
  DasborUndanganIdRoute: typeof DasborUndanganIdRoute
  DasborBukuTamuIndexRoute: typeof DasborBukuTamuIndexRoute
  DasborUndanganIndexRoute: typeof DasborUndanganIndexRoute
}

const DasborRouteChildren: DasborRouteChildren = {
  DasborAcaraRoute: DasborAcaraRoute,
  DasborCeritaRoute: DasborCeritaRoute,
  DasborGaleriRoute: DasborGaleriRoute,
  DasborHadiahRoute: DasborHadiahRoute,
  DasborMempelaiRoute: DasborMempelaiRoute,
  DasborPaketRoute: DasborPaketRoute,
  DasborPembelianRoute: DasborPembelianRoute,
  DasborProfilRoute: DasborProfilRoute,
  DasborSebarRoute: DasborSebarRoute,
  DasborTamuRoute: DasborTamuRoute,
  DasborTemplateRoute: DasborTemplateRoute,
  DasborIndexRoute: DasborIndexRoute,
  DasborBukuTamuEventIdRoute: DasborBukuTamuEventIdRouteWithChildren,
  DasborUndanganIdRoute: DasborUndanganIdRoute,
  DasborBukuTamuIndexRoute: DasborBukuTamuIndexRoute,
  DasborUndanganIndexRoute: DasborUndanganIndexRoute,
}

const DasborRouteWithChildren =
  DasborRoute._addFileChildren(DasborRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  AdminRoute: AdminRouteWithChildren,
  DasborRoute: DasborRouteWithChildren,
  FiturRoute: FiturRoute,
  LoginRoute: LoginRoute,
  MasukRoute: MasukRoute,
  BeritaSlugRoute: BeritaSlugRoute,
  DemoAiSlugRoute: DemoAiSlugRoute,
  DemoSlugRoute: DemoSlugRoute,
  BeritaIndexRoute: BeritaIndexRoute,
  DemoIndexRoute: DemoIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
